name: Main
on:
- push
- pull_request_target
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - run: sudo apt-get install libgda-5.0-dev
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - name: Lint
      run: |
        bundle exec rubocop --parallel
  automerge:
    name: AutoMerge
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && (github.actor == github.repository_owner || github.actor == 'dependabot[bot]')
    steps:
    - uses: actions/github-script@v3
      with:
        script: |
          github.pulls.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number
          })
